# PlanDoc custom override

x-common-variables: &common-variables
  POSTGRES_PASSWORD: /run/secrets/postgres_password
  DATABASE_PASSWORD: /run/secrets/postgres_password  
  SECRET_KEY: /run/secrets/secret_key
  OIDC_CLIENT_SECRETS: /run/secrets/oidc_client_secrets
  FLASK_DEBUG: false
  SUPERSET_ENV: production
  SUPERSET_LOAD_EXAMPLES: no
  PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev:/app/docker/plandoc-custom
  OIDC_OPENID_REALM: /run/secrets/oidc_openid_realm
  
x-common-secrets: &common-secrets
  - postgres_password
  - secret_key
  - oidc_client_secrets
  - oidc_openid_realm

services:
  superset:
    environment: *common-variables
    secrets: *common-secrets
    build:
      args:
         BUILD_TRANSLATIONS: true

  superset-init:
    environment: *common-variables
    secrets: *common-secrets

  superset-worker:
    environment: *common-variables
    secrets: *common-secrets

  superset-worker-beat:
    environment: *common-variables
    secrets: *common-secrets

secrets:
   postgres_password:
     file: /bases/.system/bi/POSTGRES_PASSWORD.txt
   secret_key:
     file: /bases/.system/bi/SECRET_KEY.txt
   oidc_client_secrets:
     file: /bases/.system/bi/client_secret.json
   oidc_openid_realm:
     file: /bases/.system/bi/OIDC_OPENID_REALM.txt
